---
- hosts: client
  tags:
    - client
  roles:
    - common
    - openvswitch
    - collectd
    - consul-client
    - docker

- hosts: client1
  tags:
    - docker-over-ovs
  roles:
    - docker-over-ovs
