---
  
- name: Installer collectd
  apt: name=collectd-core state=present
  become: true

- name: Configurer collectd
  copy: src=collectd.conf dest=/etc/collectd/collectd.conf
  become: true
  notify:
    - restart collectd
